baseURL = "https://www.carbontoken.info/"
languageCode = "en-us"
title = "CARBON | ZRC-2 Token"
Description = "CARBON will be used as the preferred payment method in exchange of all products, services and tools being developed by Genesys Labs as well as a growing number of other businesses."
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "CARBON"
	keywords = "CARBON,token,cryptocurrency,Zilliqa,ZRC-2"  #fallback for homepage
    description = "Zilliqa Powered ZRC-2 Token"
	SiteDescription = "CARBON will be used as the preferred payment method in exchange of all products, services and tools being developed by Genesys Labs as well as a growing number of other businesses." #fallback for homepage
    email = ""
    phone = ""
    address = ""
    lastupdated = "13th October 2020"
    year = 2018
    background = ""
    favicon = "images/logo.png"
    DateForm = "January 2, 2008"

    showSubheader = true
    showCarbonInfo = true
    showRecentNews = true
    showGetInvolved = true
    showPartners = true


    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    identifier = "treasury"
    name = "Treasury"
    url = "/treasury/"
    weight = 3

[[menu.main]]
    identifier = "uto"
    name = "UTO"
    url = "/projects/uto"
    weight = 4

[[menu.main]]
    identifier = "avatar"
    name = "AVATAR"
    url = "/projects/avatar"
    weight = 5

[params.sharethis]
    property = ""
    custom = true

[params.google.analytics]
    #trackerID = "UA-119106486-1"

[[params.social]]
	title = "facebook"
	url = ""
    icon = "fa-facebook-square"
    footer = false
    sharethis = false
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = ""
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = false
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = ""
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = ""
    icon = "fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = ""
    icon = "fa-linkedin-square"
    footer = false
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = ""
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/GenesysLabs"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = ""
    icon = "fas fa-envelope"
    footer = false
    sharethis = false
    network = "email"
[[params.social]]
    title = "telegram"
    url = "https://t.me/carbonholders"
    icon = "fab fa-telegram"
    footer = true
    sharethis = true
    network = "email"
